from enum import Enum


class MainPageTextConstants(Enum):
    TITLE = "TITLE"
    LOGIN_BUTTON_TEXT = "LOGIN_BUTTON_TEXT"
    ACCEPTED_USERNAMES_TITLE = "ACCEPTED_USERNAMES_TITLE"
    ACCEPTED_USERNAMES_VALUES = "ACCEPTED_USERNAMES_VALUES"
    PASSWORD = "PASSWORD"
